on: [push]

jobs:
  upload_spheron_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    name: A job to test upload action on spheron
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          npm ci
          npm run build --if-present
      - name: Spheron upload action step
        id: upload
        uses: theycallmeloki/spheron-upload-action@v0.36
        with:
          spheron-api-key: ${{ secrets.SPHERON_API_KEY }}
          spheron-project-name: ${{ secrets.SPHERON_PROJECT_NAME }}
          spheron-organization-id: ${{ secrets.SPHERON_ORGANIZATION_ID }}
          spheron-upload-folder: "build"
          spheron-protocol: "ipfs-pinata"
      # Use the output from the `hello` step
      - name: Get the url of the deployment
        run: echo "The url was ${{ steps.upload.outputs.site }}"
